// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDasU8cEBd3YQKWdFucp003FKV0RaUl08k',
    appId: '1:980576947065:web:1c5f04d0077c868bc0bda8',
    messagingSenderId: '980576947065',
    projectId: 'sawad-finnix',
    authDomain: 'sawad-finnix.firebaseapp.com',
    storageBucket: 'sawad-finnix.firebasestorage.app',
    measurementId: 'G-87WKB7E2FX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDElriZCapNFroEsHOepL7d_Z9soFwomBE',
    appId: '1:980576947065:android:03d19672b1282c27c0bda8',
    messagingSenderId: '980576947065',
    projectId: 'sawad-finnix',
    storageBucket: 'sawad-finnix.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiw3KHAvwc6_XYLhywYJenqF-ikZkc5Iw',
    appId: '1:980576947065:ios:b55c6f69dcef54f8c0bda8',
    messagingSenderId: '980576947065',
    projectId: 'sawad-finnix',
    storageBucket: 'sawad-finnix.firebasestorage.app',
    iosBundleId: 'com.srisawad.sawadFinnix',
  );
}
