// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_uat.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC2NhXHp30rkvntiQA44sspyaU63LI5Hw',
    appId: '1:841613032673:web:381a55265995f2b7f30ba0',
    messagingSenderId: '841613032673',
    projectId: 'sawad-finnix-uat',
    authDomain: 'sawad-finnix-uat.firebaseapp.com',
    storageBucket: 'sawad-finnix-uat.firebasestorage.app',
    measurementId: 'G-PJ0150H8EY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2uGUGZ3UjiUAwarYBYqIC9dYwj4c1x_g',
    appId: '1:841613032673:android:b4d7915da351f9adf30ba0',
    messagingSenderId: '841613032673',
    projectId: 'sawad-finnix-uat',
    storageBucket: 'sawad-finnix-uat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXLxFEKsM4GAvK5Nd7aAQADdsoRPQ4Vlc',
    appId: '1:841613032673:ios:ffccc736343b1978f30ba0',
    messagingSenderId: '841613032673',
    projectId: 'sawad-finnix-uat',
    storageBucket: 'sawad-finnix-uat.firebasestorage.app',
    iosBundleId: 'com.srisawad.sawadFinnix',
  );
}
