import 'package:firebase_core/firebase_core.dart';

import '../config/env_config.dart';
import '../../firebase_options_prod.dart' as prod;
import '../../firebase_options_uat.dart' as uat;

/// Initializes Firebase using the options matching the active environment.
///
/// Two option files are generated by `flutterfire configure` (one per Firebase
/// project). We select the correct [FirebaseOptions] at runtime based on
/// [EnvConfig], so a single codebase targets prod (`sawad-finnix`) or
/// uat (`sawad-finnix-uat`) purely from `--dart-define=ENV`.
class FirebaseInit {
  FirebaseInit._();

  static FirebaseOptions optionsFor(AppEnvironment env) {
    switch (env) {
      case AppEnvironment.prod:
        return prod.DefaultFirebaseOptions.currentPlatform;
      case AppEnvironment.uat:
        return uat.DefaultFirebaseOptions.currentPlatform;
    }
  }

  static Future<FirebaseApp> initialize(EnvConfig config) {
    return Firebase.initializeApp(
      options: optionsFor(config.environment),
    );
  }
}
